name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deps
        run: sudo apt install -y texlive texlive-lang-german latexmk
      - name: Build
        run: ./build.sh
      - name: Package
        run: ./package.sh
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/artciles.tar.gz
